In [1]:
import numpy  as np
import pandas as pd

## 1-. Obtener y analisis previo de los datos

Para obtener los datos fotometricos usamos la base de datos `SDSS DR16Q` el cual tiene aproximadamente 750.000 entradas de cuasares con datos en diferentes bandas.

Lo primero para cualquier analisis de datos es revisar la salud de nuestro dataset y de esta forma eliminar valores atipicos causados por errores randoms o encontrar algun desfaze sistematico en nuestos datos.

In [2]:
df = pd.read_csv("../data/pre_processed/SDSS_DR14Q_phot.csv")
df.describe()

,RA,DEC,Z,FUV_flux,NUV_flux,u_mag,g_mag,r_mag,i_mag,z_mag,j_mag,h_mag,k_mag,w1_mag,w2_mag,SN
count,739122.000000,739122.000000,739122.000000,739122.000000,739122.000000,739122.000000,739122.000000,739122.000000,739122.000000,739122.000000,739122.000000,739122.000000,739122.000000,739122.000000,739122.000000,739122.000000
mean,172.903002,27.838698,1.725140,0.773353,2.198870,7.534645,7.022798,6.862467,6.712097,6.559364,-0.569311,-0.586141,-0.603359,16.672392,15.620745,5.567603
std,97.034527,18.710125,2.149397,4.567057,7.358361,370.890364,371.053694,370.314855,370.309267,370.303603,2.719654,2.613567,2.505291,1.306029,1.334802,5.056252
min,0.000629,-17.520442,-999.000000,-1.320069,-1.268950,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.524078
25%,126.926378,11.329493,1.170803,-0.036561,0.000000,20.512725,20.151606,19.940748,19.796805,19.659220,-1.000000,-1.000000,-1.000000,16.007062,14.931556,2.312605
50%,175.337411,29.614477,1.679654,0.060562,0.469840,21.333239,20.931570,20.701501,20.543793,20.355373,-1.000000,-1.000000,-1.000000,16.742247,15.694827,3.969628
75%,228.276186,42.646179,2.245000,0.491472,1.872555,21.988977,21.546595,21.324998,21.160762,20.952934,-1.000000,-1.000000,-1.000000,17.419416,16.377457,7.142130
max,359.999954,84.431413,7.023917,1317.951416,1234.588745,30.888962,26.311369,26.588125,29.951653,24.465014,18.929001,18.148001,17.615999,31.134980,31.381320,76.683449

In [3]:
df_clean = df.replace([-999, -9999, -1000, -1], np.nan).dropna()
df_clean.describe()

,RA,DEC,Z,FUV_flux,NUV_flux,u_mag,g_mag,r_mag,i_mag,z_mag,j_mag,h_mag,k_mag,w1_mag,w2_mag,SN
count,14509.000000,14509.000000,14509.000000,14509.000000,14509.000000,14509.000000,14509.000000,14509.000000,14509.000000,14509.000000,14509.000000,14509.000000,14509.000000,14509.000000,14509.000000,14509.000000
mean,174.955818,25.358231,1.212100,11.883174,22.937687,18.781201,18.303709,18.076601,17.929278,17.777612,16.619732,15.965325,15.284260,14.070112,12.930021,22.884243
std,80.367523,19.129265,0.830058,27.741541,35.582390,1.267135,0.870099,0.732993,0.682152,0.644490,0.505004,0.516795,0.573014,0.795289,0.839078,10.005522
min,0.049839,-17.520442,0.004153,-0.802397,-0.731283,14.247252,14.388747,14.459475,14.084700,14.375872,13.035000,12.212000,11.374000,9.834508,8.811273,0.024650
25%,138.367612,10.020275,0.529841,0.000000,0.385281,18.055700,17.812128,17.659678,17.549417,17.436186,16.386000,15.734000,15.027000,13.603164,12.412288,15.580596
50%,178.274687,24.460883,0.977000,2.074873,11.897568,18.560076,18.241213,18.074293,17.955587,17.816260,16.688999,16.039000,15.366000,14.119801,12.946188,21.586288
75%,220.805628,39.610748,1.732794,14.256594,32.367210,19.200920,18.706896,18.470171,18.311268,18.139710,16.941999,16.283001,15.644000,14.614690,13.478512,28.843119
max,359.961213,84.431413,7.011245,1317.951416,1234.588745,26.220543,25.622784,24.802845,24.943384,23.441550,18.929001,18.148001,17.615999,17.800632,17.499205,76.683449

In [4]:
df_reduce = df_clean.loc[
    (df_clean["Z"]        <= 2.5) & 
    (df_clean["SN"]       >= 20 ) &
    (df_clean["FUV_flux"] >  0  ) &
    (df_clean["NUV_flux"] >  0  )
].reset_index(drop=True)

df_reduce.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5669 entries, 0 to 5668
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SDSS_NAME  5669 non-null   object
 1   RA         5669 non-null   float64
 2   DEC        5669 non-null   float64
 3   Z          5669 non-null   float64
 4   FUV_flux   5669 non-null   float64
 5   NUV_flux   5669 non-null   float64
 6   u_mag      5669 non-null   float64
 7   g_mag      5669 non-null   float64
 8   r_mag      5669 non-null   float64
 9   i_mag      5669 non-null   float64
 10  z_mag      5669 non-null   float64
 11  j_mag      5669 non-null   float64
 12  h_mag      5669 non-null   float64
 13  k_mag      5669 non-null   float64
 14  w1_mag     5669 non-null   float64
 15  w2_mag     5669 non-null   float64
 16  SN         5669 non-null   float64
dtypes: float64(16), object(1)
memory usage: 753.0+ KB

## Unificacion de sistemas fotometricos

Los diferentes catálogos usan sistemas de magnitudes distintos.  
Todos se convierten a **AB** antes de aplicar la corrección K.

### 2.1 GALEX (FUV, NUV)

Las columnas anteriores estan en **nanomaggies** (que chucha es eso), como queremos pasar de flujo a magnitud en sistema AB usamos 

$$
    m_{AB} = 22.5 * 2.5 \log_{10}(nMgy)
$$

> GALEX — Martin et al. 2005, ApJ 619, L1

In [5]:
df_reduce["FUV_mag"] = 22.5 - 2.5 * np.log10(df_reduce["FUV_flux"])
df_reduce["NUV_mag"] = 22.5 - 2.5 * np.log10(df_reduce["NUV_flux"])

### 2.2 2MASS (J, H, K)

Estas magnitudes se encuentran usando como candala estandar a Vega, como queremos trabajar en las magnitudes AB usamos las siguiente transformacion.

$$
\begin{aligned}
  J_{\mathrm{AB}} &= J_{\mathrm{Vega}} + 0.894 \\
  H_{\mathrm{AB}} &= H_{\mathrm{Vega}} + 1.374 \\
  K_{\mathrm{AB}} &= K_{\mathrm{Vega}} + 1.840
\end{aligned}
$$

In [6]:
df_reduce["j_mag"] = df_reduce["j_mag"] + 0.894
df_reduce["h_mag"] = df_reduce["h_mag"] + 1.374
df_reduce["k_mag"] = df_reduce["k_mag"] + 1.840

### 2.3 WISE (W1, W2)

Al igual que las magnitudes de 2MASS los datos registrados por WISE usan como candela estandar a vega, por lo tanto usamos la transformacion.

$$
  \begin{aligned}
    W1_{\mathrm{AB}} &= W1_{\mathrm{Vega}} + 2.699 \\
    W2_{\mathrm{AB}} &= W2_{\mathrm{Vega}} + 3.339
  \end{aligned}
$$

In [7]:
df_reduce["w1_mag"] = df_reduce["w1_mag"] + 2.699
df_reduce["w1_mag"] = df_reduce["w2_mag"] + 3.339

### 1.2 Correcion por extincion galactica

In [8]:
from astropy.io          import fits
from astropy.coordinates import SkyCoord
from astropy_healpix     import HEALPix

import astropy.units as u
import matplotlib.pyplot as plt

In [9]:
with fits.open("../data/dustmaps/final_dustmap_ebv.fits") as hdul:
    dustmap_header = hdul[0].header
    dustmap_data   = hdul[0].data

In [10]:
dustmap_header

SIMPLE  =                    T / conforms to FITS standard
BITPIX  =                  -32 / array data type
NAXIS   =                    1 / number of array dimensions
NAXIS1  =             50331648
PIXTYPE = 'HEALPIX '           / HEALPIX pixelisation
ORDERING= 'RING    '           / Pixel ordering scheme, either RING or NESTED
NSIDE   =                 2048 / Healpix resolution parameter
NPIX    =             50331648 / Total number of pixels
OBJECT  = 'FULLSKY '           / Sky coverage, either FULLSKY or PARTIAL
FIRSTPIX=                    0 / First pixel # (0 based)
LASTPIX =             50331647 / Last pixel # (zero based)
INDXSCHM= 'IMPLICIT'           / indexing : IMPLICIT or EXPLICIT
GRAIN   =                    0 / GRAIN = 0: No index,
COMMENT         GRAIN =1: 1 pixel index for each pixel,
COMMENT         GRAIN >1: 1 pixel index for Grain consecutive pixels
BAD_DATA=         -1.63750E+30 / Sentinel value given to bad pixels
COORDSYS= 'G       '           / Pixelization coordinate system
COMMENT         G = Galactic, E = ecliptic, C = celestial = equatorial
COMMENT         G = Galactic, E = ecliptic, C = celestial = equatorial
COMMENT ------------------------------------------------------------
COMMENT GNILC Planck dust opacity map at 353 GHz
COMMENT (CIB-removed dust opacity map produced by the GNILC method)
COMMENT Mathieu Remazeilles
COMMENT mathieu.remazeilles@manchester.ac.uk
COMMENT ------------------------------------------------------------
COMMENT Planck Collaboration, "Planck intermediate results. XLVIII.
COMMENT Disentangling Galactic dust emission and cosmic infrared
COMMENT background anisotropies", arXiv:1605.09387
COMMENT ------------------------------------------------------------
COMMENT For further details see Planck Explanatory Supplement at:
COMMENT http://www.cosmos.esa.int/planckpla-int
COMMENT ------------------------------------------------------------
COMMENT E(B-V) dust map derived from Planck GNILC TAU353
NU_REF  = '353.0   '           / Reference frequency (GHz)
FWHM    = '5.00000 '           / arcmin
POLAR   = 'False   '           / Polarization included (True/False)
POLCCONV= 'COSMO   '           / Coord. convention for polarisation COSMO/IAU)
METHOD  = 'GNILC   '           / Component Separation method
AST-COMP= 'DUST    '           / Astrophysical component name
FILENAME= 'COM_CompMap_Dust-GNILC-Model-Opacity_2048_R2.00.fits ' / FITS filenam
DATE    = '2016-08-31'         / Creation date of FITS header
BUNIT   = 'mag     '
K_TAU   =              14900.0 / Conversion factor from tau353 to E(B-V)

In [12]:
sky_coords = SkyCoord(
    ra  = df_reduce["RA"].to_numpy()  * u.deg, 
    dec = df_reduce["DEC"].to_numpy() * u.deg,
    frame="icrs"
)

hp = HEALPix(
    nside = 2048, 
    order = "NESTED", 
    frame = "icrs"
)

ebv = hp.interpolate_bilinear_lonlat(
    sky_coords.ra,
    sky_coords.dec,
    dustmap_data
)

ebv = np.clip(ebv, 0.0, None)

In [13]:
# ---
df_reduce["A_fuv"] = 8.24 * ebv
df_reduce["A_nuv"] = 8.20 * ebv

# SDSS (Schlafly & Finkbeiner 2011)
df_reduce["A_u"] = 4.239 * ebv
df_reduce["A_g"] = 3.303 * ebv
df_reduce["A_r"] = 2.285 * ebv
df_reduce["A_i"] = 1.698 * ebv
df_reduce["A_z"] = 1.263 * ebv

# --- 
df_reduce["A_j"] = 0.709 * ebv
df_reduce["A_h"] = 0.449 * ebv
df_reduce["A_k"] = 0.302 * ebv

# ---
df_reduce["A_w1"] = 0.18 * ebv
df_reduce["A_w2"] = 0.15 * ebv

### 1.3 Correccion K (template)

dsadsa

In [ ]:
def kr_correction (lam, filter_lam, filter_thr, spect_flx, z):
    # Valores del filtro interpolado
    R0 = np.interp(lam,       filter_lam, filter_thr, left=0.0, right=0.0)
    Rz = np.interp((1+z)*lam, filter_lam, filter_thr, left=0.0, right=0.0)

    # Integrales con el factor λ (fotones)
    num = np.trapezoid(spect_flx * Rz * lam, lam)
    den = np.trapezoid(spect_flx * R0 * lam, lam)

    # K-correction (misma banda)
    K = -2.5 * np.log10((1.0 + z) * (num / den))
    
    return float(K)

In [17]:
def open_filter (filepath):
    data = np.loadtxt(filepath)
    return data[:, 0], data[:, 1]

In [19]:
FILTER_GALEX_FUV = open_filter("../data/filters/GALEX_GALEX.FUV.dat")
FILTER_GALEX_NUV = open_filter("../data/filters/GALEX_GALEX.NUV.dat")

FILTER_PSFMAG_U = open_filter("../data/filters/SLOAN_SDSS.u.dat")
FILTER_PSFMAG_G = open_filter("../data/filters/SLOAN_SDSS.g.dat")
FILTER_PSFMAG_R = open_filter("../data/filters/SLOAN_SDSS.r.dat")
FILTER_PSFMAG_I = open_filter("../data/filters/SLOAN_SDSS.i.dat")
FILTER_PSFMAG_Z = open_filter("../data/filters/SLOAN_SDSS.z.dat")

FILTER_2MASS_J = open_filter("../data/filters/2MASS_2MASS.J.dat")
FILTER_2MASS_H = open_filter("../data/filters/2MASS_2MASS.H.dat")
FILTER_2MASS_K = open_filter("../data/filters/2MASS_2MASS.K.dat")

FILTER_WISE_W1 = open_filter("../data/filters/WISE_WISE.W1.dat")
FILTER_WISE_W2 = open_filter("../data/filters/WISE_WISE.W2.dat")

In [23]:
TEMPLATE_DATA = np.loadtxt("../data/templates/template_extendido.dat", skiprows=4)

ValueError: could not convert string '860.432000,9.054480e-16' to float64 at row 0, column 1.

In [22]:
K = kr_correction(
    TEMPLATE_DATA[:, 0],
    FILTER_GALEX_FUV[:, 0],
    FILTER_GALEX_FUV[:, 1], 
    TEMPLATE_DATA[:, 1],
    df_reduce["Z"].to_numpy()
)

K

NameError: name 'TEMPLATE_DATA' is not defined